from typing import Awaitable, Callable, Optional, Protocol

SessionReleaseHandler = Callable[[dict[str, object]], Awaitable[None]]
TicketExpiredHandler = Callable[[str], Awaitable[None]]


class SessionManager(Protocol):
    queue_enabled: bool

    def set_abnormal_disconnect_handler(self, handler: Optional[SessionReleaseHandler]) -> None: ...

    def set_ticket_expired_handler(self, handler: Optional[TicketExpiredHandler]) -> None: ...

    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def allocate(
        self, lb_base_url: str, *, llm_fingerprint: Optional[str] = None, pipeline: Optional[str] = None
    ) -> dict[str, object]: ...

    async def poll(self, ticket_id: str, lb_base_url: str) -> dict[str, object]: ...

    async def leave(self, ticket_id: str) -> bool: ...

    async def cancel_pending_session(self, session_id: str) -> None: ...

    async def handle_event(self, session_id: str, session_token: str, event: str) -> dict[str, object]: ...

    async def healthcheck(self) -> tuple[bool, Optional[str], dict[str, object]]: ...
